name: Build and Deploy Code

# spesify to triger push or pull
on: [push, pull_request]

jobs:
  job1:
    env: # store the secret in Github
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ACCESS_TOKEN_EXPIRE_MIN: ${{secrets.ACCESS_TOKEN_EXPIRE_MIN}}
      ALGORITHM: ${{secrets.ALGORITHM}}
    # specifiy what machine to run the progrom
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi to zhaoming
        run: echo "hello zhaoming"
      # install python
      - name: Install python version 3.9
        uses: actions/checkout@v3
        with:
          python-version: '3.9'
      - name: upgrade pip
        run: python -m pip install --upgrade pip # commend to upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt # install all packages in requirments.txt
      - name: install pytest
        run: pip install pytest
      - name: test with pytest
        run: pytest