name: Build and Deploy Code

# spesify to triger push or pull
on: [push, pull_request]

jobs:
  job1:
    # specifiy what machine to run the progrom
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi to zhaoming
        run: echo "hello zhaoming"
      # install python
      - name: Install python version 3.9
        uses: actions/checkout@v3
        with:
          python-version: '3.9'
      - name: upgrade pip
        run: python -m pip install --upgrade pip # commend to upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt