name: Build and Deploy Code

# spesify to triger push or pull
on: [push, pull_request]

jobs:
  job1:
    env: # store the secret in Github
      DATABASE_HOST: ${{secret.DATABASE_HOST}}
      DATABASE_NAME: fastapi
      DATABASE_PASSWORD: 991230
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      SECRET_KEY: joiz7fhjeiou8awe79823rhfi3
      ACCESS_TOKEN_EXPIRE_MIN: 60
      ALGORITHM: HS256
    # specifiy what machine to run the progrom
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi to zhaoming
        run: echo "hello zhaoming"
      # install python
      - name: Install python version 3.9
        uses: actions/checkout@v3
        with:
          python-version: '3.9'
      - name: upgrade pip
        run: python -m pip install --upgrade pip # commend to upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt # install all packages in requirments.txt
      - name: test with pytest
        run:
          pip install pytest
          pytest